name: 'Lando Start'
description: 'Spin up amp website'
inputs:
  GH_TOKEN_REPO:
    description: "PAT"
    required: true
  GITHUB_TOKEN:
    description: "Github token"
    required: true
  DATABASE:
    description: "Use specific backup"
    required: false

runs:
  using: "composite"
  steps:
    - name: Custom DATABASE
      run: echo "DATABASE=$( $DATABASE )" >> $GITHUB_ENV
      env:
        DATABASE: ${{ inputs.DATABASE }}
      shell: bash

    - name: Set lando version.
      run: echo "LANDO_VERSION=$(cat .github/lando_version.md)" >> $GITHUB_ENV
      shell: bash

    - name: Install Lando
      run: |
        sudo curl -fsSL -o /usr/local/bin/lando "https://files.lando.dev/cli/lando-linux-x64-$LANDO_VERSION"
        sudo chmod +x /usr/local/bin/lando
      shell: bash

    - name: Composer install
      run: |
        composer config -g github-oauth.github.com $gh_token
        composer install --ignore-platform-reqs --prefer-dist -n
      shell: bash
      env:
        gh_token: ${{ inputs.GH_TOKEN_REPO }}

    - name: Last Sunday date
      run: echo "LAST_SUNDAY=$(date -d "last Sunday" +%Y-%m-%d)" >> $GITHUB_ENV
      shell: bash

    - name: Todays date
      run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
      shell: bash

    - name: Spin up site
      run: |
        composer config -g github-oauth.github.com $gh_token
        vendor/bin/blt amp:landosetup $gh_token 1
      shell: bash
      env:
        gh_token: ${{ inputs.GH_TOKEN_REPO }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: Custom Database
      if: "${{ env.DATABASE != '' }}"
      run: |
        rm backups/site.sql.gz
        wget -O backups/site.sql.gz '$DATABASE'
        lando db-import backups/site.sql.gz
        lando drush sql-sanitize --sanitize-password -y
        chmod u+x .keys/createTestUsers.sh
        lando ssh -c /app/.keys/createTestUsers.sh
        lando drush en oit_dev
        lando drush en dblog devel devel_kint_extras
      shell: bash

