name: 'Lando Start'
description: 'Spin up amp website'
inputs:
  GH_TOKEN_REPO:
    description: "PAT"
    required: true
  GITHUB_TOKEN:
    description: "Github token"
    required: true
  DATABASE:
    description: "Use specific backup"
    required: false

runs:
  using: "composite"
  steps:
    - name: Custom DATABASE
      run: echo "DATABASE=$( $DATABASE )" >> $GITHUB_ENV
      env:
        DATABASE: ${{ inputs.DATABASE }}
      shell: bash

    - name: Set lando version.
      run: echo "LANDO_VERSION=$(cat .github/lando_version.md)" >> $GITHUB_ENV
      shell: bash

    - name: Cache Lando
      id: cache-lando
      uses: actions/cache@v3
      with:
        path: /usr/local/bin/lando
        key: lando-${{ runner.os }}-${{ env.LANDO_VERSION }}

    - name: Install Lando
      if: steps.cache-lando.outputs.cache-hit != 'true'
      run: |
        sudo curl -fsSL -o /usr/local/bin/lando "https://files.lando.dev/cli/lando-linux-x64-$LANDO_VERSION"
        sudo chmod +x /usr/local/bin/lando
      shell: bash

    - name: Composer cache directory
      run: echo "COMPOSER_DIR=$(composer config cache-dir)" >> $GITHUB_ENV
      shell: bash

    - name: Cache Composer dependencies
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: "${{ env.COMPOSER_DIR }}"
        key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - name: Cache Access theme
      id: access-theme-cache
      uses: actions/cache@v3
      with:
        path: "docroot/themes/custom/accesstheme"
        key: access-theme-${{ runner.os }}-${{ hashFiles('docroot/themes/custom/accesstheme') }}

    - name: Composer install
      run: |
        composer config -g github-oauth.github.com $gh_token
        composer install --ignore-platform-reqs --prefer-dist -n
      shell: bash
      env:
        gh_token: ${{ inputs.GH_TOKEN_REPO }}

    - name: Last Sunday date
      run: echo "LAST_SUNDAY=$(date -d "last Sunday" +%Y-%m-%d)" >> $GITHUB_ENV
      shell: bash

    - name: Todays date
      run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
      shell: bash

    - name: Cache Files
      id: drupal-files-cache
      uses: actions/cache@v3
      with:
        path: |
          web/sites/default/files
          files-private
        key: ${{ runner.os }}-${{ env.LAST_SUNDAY }}-files

    - name: Daily db cache
      id: drupal-db-cache
      uses: actions/cache@v3
      with:
        path: backups
        key: ${{ runner.os }}-${{ env.DATE }}-db

    - name: Spin up site
      run: |
        composer config -g github-oauth.github.com $gh_token
        vendor/bin/blt amp:landosetup $gh_token 1
      shell: bash
      env:
        gh_token: ${{ inputs.GH_TOKEN_REPO }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: Custom Database
      if: "${{ env.DATABASE != '' }}"
      run: |
        rm backups/site.sql.gz
        wget -O backups/site.sql.gz '$DATABASE'
        lando db-import backups/site.sql.gz
        lando drush sql-sanitize --sanitize-password -y
        chmod u+x .keys/createTestUsers.sh
        lando ssh -c /app/.keys/createTestUsers.sh
        lando drush en oit_dev
        lando drush en dblog devel devel_kint_extras
      shell: bash

